config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :wikis
  resources :charges
  resources :users, only: [:create]
  resources :collaborators, only: [:create, :destroy]

  get "welcome/index"
  get 'about' => 'welcome#about'
  get 'downgrade' =>'users#downgrade'

  root 'welcome#index'

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :wikis
  has_many :collaborators
  has_many :collab_wikis, :through => :collaborators, source: :wiki

  enum role: [:standard, :premium, :admin]

  before_save { self.role ||= :standard}

  def standard?
    role == "standard"
  end

  def premium?
    role == "premium"
  end

  def admin?
    role == "admin"
  end

  def upgrade
    self.update_attribute(:role, :premium)
    self.save
  end

  def downgrade
    self.update_attribute(:role, :standard)
    make_wikis_public
    self.save
  end

  def make_wikis_public
    self.wikis.each do |wikis|
      wikis.update(private: false)
    end
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user

  has_many :collaborators
  has_many :users, :through => :collaborators

  scope :visible_to, -> (user) { user ? all : where(private: false) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include Pundit
  before_filter :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :first_name, :last_name) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :first_name, :last_name) }
    # devise_parameter_sanitizer.permit(:sign_up) do |user_params|
    #   user_params.permit(:email, :password, :password_confirmation, :first_name, :last_name)
    # end
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Premium Membership for #{current_user.email}",
      amount: 1500
    }
  end

  def create
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: 1500,
      description: "Premium Membership for #{current_user.email}",
      currency: 'usd'
   )

    flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
    current_user.premium!
    redirect_to root_path(current_user)

    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  # def index
  # end
  #
  # def new
  #   @collaborator = Collaborator.new
  #   @user = User.all
  #   @wiki = Wiki.find(params[:wiki_id])
  # end

  def create
    @wiki = Wiki.find(params[:collaborator][:wiki_id])
    @collaborator = @wiki.collaborators.build(user_id: params[:collaborator][:user_id])

    if @collaborator.save
      flash[:notice] = "A new collaborator has been added to your wiki."
      redirect_to edit_wiki_path(@wiki)
    else
      flash[:error] = "There was an error adding this collaborator. Please try again."
      render :new
    end
  end

  # def show
  #   @collaborator = Collaborator.find(params[:wiki])
  # end

  def destroy
    @collaborator = Collaborator.find(params[:id])
    wiki = @collaborator.wiki

    if @collaborator.destroy
      flash[:notice] = "Collaborator has been removed from this wiki."
    else
      flash[:error] = "There was an error removing this collaborator."
    end
    redirect_to edit_wiki_path(wiki)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.name = params[:user][:name]
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]

    if @user.save
      flash[:notice] = "Welcome to Blocipedia #{@user.name}!"
      redirect_to root_path
    else
      flash.now[:alert] = "There was an error creating your account. Please try again."
      render :new
    end
  end

  def index
    @users = User.all
  end

  def show
  end

  def downgrade
    if current_user.downgrade
      flash[:notice] = "You're account is now standard."
      redirect_to root_path
    else
      flash[:notice] = "Something went wrong. Please try again."
      redirect_to edit_user_registration_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authorize_user

  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  # before_action :authorize_user, only: [:destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
    @user = current_user
    authorize @wiki
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user
    @wiki.private = params[:wiki][:private]
    authorize @wiki

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @collaborator = Collaborator.new
    @wiki = Wiki.find(params[:id])
    @collaborators = @wiki.collaborators
    collab_users = @wiki.users
    @users = User.where.not(id: current_user.id).map{|u| [u.email, u.id] unless collab_users.include?(u)}.compact
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)
    @wiki.private = params[:wiki][:private]
    authorize @wiki

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end

private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end

  # def authorize_user
  #   @wiki = Wiki.find(params[:id])
  #   unless current_user == @wiki.user || current_user.admin?
  #     flash[:alert] = "You must be an admin to do that."
  #     redirect_to @wiki
  #   end
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
  def user_is_authorized_to_delete_wiki?
    current_user == @wiki.user || current_user.admin?
  end

  def markdown_to_html(markdown_string)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    output = markdown.render(markdown_string)
    "<div class='markdown'>#{output}</div>".html_safe
  end
end

app/views/charges/new.html.erb
<div class="container">
<%= form_tag charges_path do %>
  <h4>Click here to upgrade!</h4>
     <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
  <% end %>
</div>

app/views/collaborators/_create.html.erb
<div class="col-md-6">
<%= form_for @collaborator do |f| %>
  <%= f.select :user_id, @users, include_blank: true %>
  <%= f.hidden_field :wiki_id, value: @wiki.id %>
  <%= f.submit "Add Collaborator" %>
<% end %>
</div>

app/views/collaborators/_destroy.html.erb
<div class="col-md-6">
<%= form_tag collaborators_path, method: :post do %>
  <%= text_field_tag :email %>
  <%= hidden_field_tag :wiki_id, @wiki.id %>
  <%= submit_tag "Delete Collaborator" %>
  <%= flash[:notice] = "Collaborator has been removed from this wiki." %>
 <% end %>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <ul class="nav nav-tabs">
       <li><%= link_to "Home", root_path %></li>
       <li><%= link_to "About", about_path %></li>
    </ul>
  <%= yield %>
    <% if user_signed_in? %>
      Signed in as: <strong><%= current_user.email %></strong> |
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
      <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/users/new.html.erb
<h2>Sign up</h2>

 <div class="row">
   <div class="col-md-8">
     <%= form_for @user do |f| %>
       <% if @user.errors.any? %>
         <div class="alert alert-danger">
           <h4><%= pluralize(@user.errors.count, "error") %>.</h4>
           <ul>
             <% @user.errors.full_messages.each do |msg| %>
               <li><%= msg %></li>
             <% end %>
           </ul>
         </div>
       <% end %>
       <%= form_group_tag(@user.errors[:name]) do %>
         <%= f.label :name %>
         <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: "Enter name" %>
       <% end %>
       <%= form_group_tag(@user.errors[:email]) do %>
         <%= f.label :email %>
         <%= f.email_field :email, class: 'form-control', placeholder: "Enter email" %>
       <% end %>
       <%= form_group_tag(@user.errors[:password]) do %>
         <%= f.label :password %>
         <%= f.password_field :password, class: 'form-control', placeholder: "Enter password" %>
       <% end %>
       <%= form_group_tag(@user.errors[:password_confirmation]) do %>
         <%= f.label :password_confirmation %>
         <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Enter password confirmation" %>
       <% end %>
       <div class="form-group">
         <%= f.submit "Sign up", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/welcome/about.html.erb
<h1>About Blocipedia</h1>
<p>Created by Stephanie Dunning with help from my mentor at Bloc.io</p>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
  <h1 style="background-color: #A9A9A9;">Welcome to Blocipedia!</h1>
  <p id="index-title">Blocipedia is an application that allows users to make their own wikis.</p>
</div>

app/views/wikis/_form.html.erb
<div class="container">
  <%= form_for @wiki do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
    </div>
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
    </div>

    <% if current_user.admin? || current_user.premium? %>
      <div class="form-group">
        <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private wiki
      <% end %>
      </div>
      <% end %>
    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>
<div class="col-md-6">
  <%= render partial: 'wikis/form' %>
  <h3>Add Collaborators</h3>
  <%= render partial: 'collaborators/create', locals: {wiki: @wiki} %>
</div>
<h3>Collaborator List</h3>
<% @wiki.collaborators.each do |c| %>
  <%= c.user.full_name %> - <%= link_to "Delete", collaborator_path(c), method: :delete %><br>
<% end %>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>

<% if current_user %>
  <div class="pull-right col-md-4">
    <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
  </div>
<% end %>

<% @wikis.each do |wiki| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to wiki.title, wiki %>
      </h4>
    </div>
  </div>
<% end %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      </div>
      <div class= "col-md-12">
        <% if current_user.admin? || current_user.premium? %>
          <div class="form-group">
            <%= f.label :private, class: 'checkbox' do %>
              <%= f.check_box :private %> Private wiki
            <% end %>
          </div>
        <% end %>
         <div class="form-group">
           <%= f.submit "Save", class: 'btn btn-success' %>
         </div>
       <% end %>
     </div>
   </div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>

 <div class="row">
   <div class="col-md-8">
     <p><%= markdown_to_html(@wiki.body) %></p>
   </div>
 </div>
 <div class="row">
   <div class="col-md-8">
     <p>Private: <%= @wiki.private ? 'Yes' : 'No' %></p>
   </div>
 </div>
 <div class="row">
   <div class="col-md-4">
     <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
     <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
   </div>
 </div>